---
title: "**About Me**"

---

I am an ESPN and D1 Broadcaster along with being the Sports Director of 90.5 WASU FM The App. I have been the Sports Director for 2 years and have broadcast for four years in the following sports: Football, Basketball, Baseball, Softball, Soccer, and Volleyball.  I am a graduate of Appalachian State with degrees in Mass Media Communication and Mathematics. 

I am the voice of Appalachian State Women's Basketball on the Appalachian State IMG network. I am also the North Wilkes High School football broadcaster for 3wc radio in Wilkesboro. I host the sports talk show, SportWrApp, every Tuesday and Thursday at 6 on 90.5 WASU and the morning show, The Morning App, every Monday, Wednesday, and Friday at 8. I do freelance broadcasting work for High School and College sports. 
I am a graduate of the Kellar radio Talent Institute back in 2016 and am RAB (Radio Advertising Bureau) Certified. I interned with the David Glenn Show in 2017 and the Asheville Radio Group in 2018.

I was born in Toledo, Ohio and moved to Polk County North Carolina about a year later and have remained there ever since. I have one older sister and two younger brothers. 

